// import localFont from 'next/font/local'
import { Nunito } from "next/font/google";
import "./globals.css";
import Head from 'next/head'

import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import Navbar from "./components/navbar";

const nunito = Nunito({ subsets: ["latin"] });

// const NunitoLocal = localFont({ src: './Nunito/Nunito-VariableFont_wght.ttf' })
// const DankMono = localFont({ src: './fonts/DankMono-italic.otf' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="./images/favicon.ico" />
      </Head>
      {/* <body className={NunitoLocal.className}> */}
        {/* <body> */}
        {/* <body className={inter.className}> */}
        <body className={nunito.className}>
        <Navbar />
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
